export const errors = {
    en: {
        "invalidAddress": "Not a valid address",
        "adminWithSameEmail": "Admin with {{email}} Id already exist.",
        "noSuchAccount": "No such account exist with this email.",
        "WrongPassword": "Wrong Password Please fill Correct Password.",
        "invalidPickupAddress": "Not a valid pickup address.",
        "invalidDeliveryAddress": "Not a valid delivery address.",
        "accountAlreadyExist": "Account with given Phone number and Role already exist.",
        "noSuchAccountExist": "No such account exist.",
        "invalidMongoId": "{{key}} must be a valid mongo ID",
        "noDatafound": "No Record Found",
        "modelFound": "With this Name Model already exist",
        "alreadyExist": "Already Exists",
        "userExist": "User already Exist",
        "phoneNumberTaken": "Phone number already taken by some other user.",
        "invalidAction": "Invalid action",
        "unprocessableEntity": "Unprocessable entity",
        "somethingwrong": "Something went wrong",
        "bookingStatusError": "Status can't be changed from '{{old}}' state to '{{new}}' state.",
        "accountBlocked": "Account blocked by admin.",
        "sessionExpired": "Session expired! Please login again.",
        "noToken": "Invalid token",
        "unAuthRole": "Unauthorized role! Access denied",
        "incorrectOldPass": "Please enter correct old password",
        "accountUnverifiedAdmin": "Your Account is unverified, please contact Admin",
    },
    mace: {
        "invalidAddress": "Not a valid address",
        "adminWithSameEmail": "Admin with same Email already exist.",
        "noSuchAccount": "No such account exist with this email.",
        "WrongPassword": "Wrong Password Please fill Correct Password.",
        "invalidPickupAddress": "Not a valid pickup address.",
        "invalidDeliveryAddress": "Not a valid delivery address.",
        "accountAlreadyExist": "Account with given Phone number and Role already exist.",
        "noSuchAccountExist": "No such account exist.",
        "invalidMongoId": "{{key}} must be a valid mongo ID",
        "noDatafound": "No Record Found",
        "modelFound": "With this Name Model already exist",
        "alreadyExist": "Already Exists",
        "userExist": "Корисникот веќе излегува",
        "phoneNumberTaken": "Phone number already taken by some other user.",
        "invalidAction": "Invalid action",
        "unprocessableEntity": "Unprocessable entity",
        "somethingwrong": "Something went wrong",
        "bookingStatusError": "Status can't be changed from '{{old}}' state to '{{new}}' state.",
        "accountBlocked": "Account blocked by admin.",
        "sessionExpired": "Session expired! Please login again.",
        "noToken": "Invalid token",
        "unAuthRole": "Unauthorized role! Access denied",
        "incorrectOldPass": "Please enter correct old password",
        "accountUnverifiedAdmin": "Your Account is unverified, please contact Admin",
       
    }
}



export const success = {
    en: {
        "signupSuccessful": "Signup sucessfully",
        "loginSuccessful": "Login sucessfully",
        "accountExists": "Account already exist",
        "noSuchAccountExist": "No such account exist",
        "kycDone": "KYC Has been done sucessfully",
        "kycDetails": "KYC details fetched sucessfully",
        "gotUserProfile": "Got user profile sucessfully",
        "recordFetched": "Record fetched sucessfully",
        "updateSuccessful": "Update profile sucessfully",
        "respondSuccess": "You have responded successfully",
        "RecordFound": "Record found",
        "VehicleAdded": "Vehicle added sucessfully",
        "deleteVendor": "Delete vehicle sucessfully",
        "vendorGot": "Got Vehicle sucessfully",
        "updateVendor": "Update vehicle sucessfully",
        "bookingUpdated": "Booking status changed successfully",
        "addressRemoved": "Address Removed",
        "issueReported": "issue Reported Successfully",
        "bookingGenerated": "booking Generated Successfully",
        "logOutSuccessful": "User logOut successfully",
        "userComment": "User Comments successfully",

    },
    mace: {
        "signupSuccessful": "Signup sucessfully",
        "loginSuccessful": "Login sucessfully",
        "accountExists": "Account already exist",
        "noSuchAccountExist": "No such account exist",
        "kycDone": "KYC Has been done sucessfully",
        "kycDetails": "KYC details fetched sucessfully",
        "gotUserProfile": "Got user profile sucessfully",
        "recordFetched": "Record fetched sucessfully",
        "updateSuccessful": "Update profile sucessfully",
        "respondSuccess": "You have responded successfully",
        "RecordFound": "Record found",
        "VehicleAdded": "Vehicle added sucessfully",
        "deleteVendor": "Delete vehicle sucessfully",
        "vendorGot": "Got Vehicle sucessfully",
        "updateVendor": "Update vehicle sucessfully",
        "bookingUpdated": "Booking status changed successfully",
        "addressRemoved": "Address Removed",
        "issueReported": "issue Reported Successfully",
        "bookingGenerated": "booking Generated Successfully",
        "logOutSuccessful": "User logOut successfully",
        "userComment": "User Comments successfully",

    }
}


